### ISSUE TITLE
An error has occured in allocating shared memory: File exists

### ISSUE THREAD

**Issue by alorchhota** [Jiefei-Wang/SharedObject#8] opened 2020-10-09 18:15 UTC
Hi,

I'm using your package in my script to share objects in R. It generally works for me. However, I often (not always) get the following error, especially when I run multiple scripts at a time in a computing cluster.

```
Error in C_createSharedMemory(x, dataInfo) :
  An error has occured in allocating shared memory: File exists
```

I'm sorry that I don't have any specific recipe to reproduce the error. But I can say that I use to share a  (~10^6 x 2)-dimensional matrix in each of my script, and I run 50+ scripts at a time in a cluster.

Could you please help me resolve the issue?

**Comment by alorchhota** [comment] 2020-10-10 00:00
If it was not clear, i'm using the `share()` function.

**Comment by Jiefei-Wang** [comment] 2020-10-12 22:44
Hi @alorchhota , thanks for letting me know your problem. This might be a race condition because the package is initially designed to be ran at a single master process. There is no synchronization mechanism to make sure the IDs of the newly created shared objects from multiple processes are unique, so if you create multiple shared objects in multiple processes, it can cause the error you saw. This should be a bug in the package and I will try to fix it.

If you are impatient, you can use `synchronicity` package. What you need to do is to use a lock to make sure the creation of the shared objects be done sequentially. This might be able to solve the problem.

Best,
Jiefei

**Comment by alorchhota** [comment] 2020-10-12 23:44
Hi @Jiefei-Wang, thanks for clarification. While I can handle the issue on my side, I believe synchronized object creation would be a great addition to the package. It would make the package more useful.

**Comment by alorchhota** [comment] 2020-10-26 05:53
Thanks for making the share() function process-safe.

**Comment by Jiefei-Wang** [comment] 2020-10-26 13:26
You are welcome. JFYI, please update your package through Bioconductor. The one in Bioconductor should be more stable than the one in the current master branch. The changes should be available in Bioconductor now. Please feel free to reopen the issue if you still have the same problem after the update.

Best,
Jiefei

**Comment by alorchhota** [comment] 2020-10-26 21:06
Hi, I actually need to reopen the issue. A few days ago, I could install SharedObject (1.3.21) from Bioconductor 3.12 (devel) on my mac laptop. Today, I could not install the package from Bioconductor 3.12 on a linux cluster. However, I could install the package (1.22) from Bioconductor 3.11.

Here is the log:
```
> BiocManager::install("SharedObject")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'SharedObject'
trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/SharedObject_1.3.21.tar.gz'
Content type 'application/x-gzip' length 1650200 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘SharedObject’ ...
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for shm_open in -lrt... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
rm -f "../inst/include/SharedObject/sharedMemory.h" &&\
 rm -f "../inst/usrlib/SharedObject.a" &&\
 mkdir -p ../inst/include&&\
 mkdir -p ../inst/include/SharedObject&&\
 mkdir -p ../inst/usrlib
g++ -std=gnu++11 -I"/software/apps/R/4.0.2/gcc/5.5.0/lib64/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/BH/include' -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c C_interface.cpp -o C_interface.o
g++ -std=gnu++11 -I"/software/apps/R/4.0.2/gcc/5.5.0/lib64/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/BH/include' -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/software/apps/R/4.0.2/gcc/5.5.0/lib64/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/BH/include' -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c altrepRegistration.cpp -o altrepRegistration.o
g++ -std=gnu++11 -I"/software/apps/R/4.0.2/gcc/5.5.0/lib64/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/BH/include' -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c sharedMemory.cpp -o sharedMemory.o
sharedMemory.cpp:37:13: error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type
 static std::atomic_uint64_t *lastId;
             ^
sharedMemory.cpp: In function ‘uint32_t getNextId()’:
sharedMemory.cpp:107:25: error: ‘lastId’ was not declared in this scope
  uint32_t initial_id = *lastId;
                         ^
sharedMemory.cpp: In function ‘int32_t getLastIndex()’:
sharedMemory.cpp:122:10: error: ‘lastId’ was not declared in this scope
  return *lastId;
          ^
sharedMemory.cpp: In function ‘void initialPkgData()’:
sharedMemory.cpp:514:6: error: ‘lastId’ was not declared in this scope
  if (lastId == nullptr)
      ^
sharedMemory.cpp:525:48: error: ‘atomic_uint64_t’ is not a member of ‘std’
      allocateSharedMemoryInternal(name, sizeof(std::atomic_uint64_t));
                                                ^
sharedMemory.cpp:527:25: error: expected type-specifier
      lastId = new (ptr) std::atomic_uint64_t(0);

sharedMemory.cpp:533:15: error: ‘atomic_uint64_t’ is not a member of ‘std’
     lastId = (std::atomic_uint64_t *)mapSharedMemoryInternal(name);
               ^
sharedMemory.cpp:533:37: error: expected primary-expression before ‘)’ token
     lastId = (std::atomic_uint64_t *)mapSharedMemoryInternal(name);
                                     ^
sharedMemory.cpp: In function ‘void releasePkgData()’:
sharedMemory.cpp:548:2: error: ‘lastId’ was not declared in this scope
  lastId = nullptr;
  ^
make: *** [sharedMemory.o] Error 1
ERROR: compilation failed for package ‘SharedObject’
* removing ‘/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/SharedObject’
* restoring previous ‘/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/SharedObject’

The downloaded source packages are in
        ‘/tmp/RtmplAbMle/downloaded_packages’
Installation path not writeable, unable to update packages: nlme
Old packages: 'SharedObject'
Warning message:
In install.packages(...) :
  installation of package ‘SharedObject’ had non-zero exit status

```


Session Info:
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /software/apps/R/4.0.2/gcc/5.5.0/lib64/R/lib/libRblas.so
LAPACK: /software/apps/R/4.0.2/gcc/5.5.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.2

```

**Comment by alorchhota** [comment] 2020-10-26 21:16
Probably solution to "_sharedMemory.cpp:37:13: error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type_": https://github.com/tangrams/tangram-es/issues/2068 ?

**Comment by Jiefei-Wang** [comment] 2020-10-27 02:12
Thank you @alorchhota .  I think the link you posted is the same issue. I'll fix it today.

Best,
Jiefei

**Comment by Jiefei-Wang** [comment] 2020-10-27 10:20
Hi @alorchhota , it seems like installing CentOS is not a trivial job. Would you able to confirm the last commit in the master branch works for you? If you have `devtools` it can be installed via `devtools::install_github("https://github.com/Jiefei-Wang/SharedObject")`. Thanks!

**Comment by alorchhota** [comment] 2020-10-27 14:40
I still get the same problem. I guess, `atomic_uint64_t` needs to be replaced by `std::atomic<std::uint64_t>`, even though they are supposed to do the same thing.

Anyway, here is the log when I tried to install the package from github.
```
Downloading GitHub repo Jiefei-Wang/SharedObject@HEAD

Skipping 1 packages ahead of CRAN: BiocGenerics
  ^M   checking for file ‘/tmp/Rtmp93VFJ4/remotes51f482fbd4095/Jiefei-Wang-SharedObject-32aa6c2/DESCRIPTION’ ...^M  ^M✔  checking for file ‘/tmp/Rtmp93VFJ4/remotes51f482fbd4095/Jiefei-Wang-SharedObject-32aa6c2/DESCRIPTION’ (428ms)
^M  ^M─  preparing ‘SharedObject’:
^M  ^M   checking DESCRIPTION meta-information ...^M  ^M✔  checking DESCRIPTION meta-information
^M  ^M─  cleaning src
^M  ^M─  checking for LF line-endings in source and make files and shell scripts
^M  ^M─  checking for empty or unneeded directories
^M  ^M   Removed empty directory ‘SharedObject/inst’
^M  ^M─  building ‘SharedObject_1.3.22.tar.gz’
^M  ^M
^MInstalling package into ‘/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘SharedObject’ ...
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for shm_open in -lrt... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
rm -f "../inst/include/SharedObject/sharedMemory.h" &&\
 rm -f "../inst/usrlib/SharedObject.a" &&\
 mkdir -p ../inst/include&&\
 mkdir -p ../inst/include/SharedObject&&\
 mkdir -p ../inst/usrlib
g++ -std=gnu++11 -I"/software/apps/R/4.0.2/gcc/5.5.0/lib64/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/BH/include' -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c C_interface.cpp -o C_interface.o
g++ -std=gnu++11 -I"/software/apps/R/4.0.2/gcc/5.5.0/lib64/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/BH/include' -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/software/apps/R/4.0.2/gcc/5.5.0/lib64/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/BH/include' -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c altrepRegistration.cpp -o altrepRegistration.o
g++ -std=gnu++11 -I"/software/apps/R/4.0.2/gcc/5.5.0/lib64/R/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/BH/include' -I'/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c sharedMemory.cpp -o sharedMemory.o
sharedMemory.cpp:38:13: error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type
 static std::atomic_uint64_t *lastId;
             ^
sharedMemory.cpp: In function ‘uint32_t getNextId()’:
sharedMemory.cpp:108:25: error: ‘lastId’ was not declared in this scope
  uint32_t initial_id = *lastId;
                         ^
sharedMemory.cpp: In function ‘int32_t getLastIndex()’:
sharedMemory.cpp:123:10: error: ‘lastId’ was not declared in this scope
  return *lastId;
          ^
sharedMemory.cpp: In function ‘void initialPkgData()’:
sharedMemory.cpp:515:6: error: ‘lastId’ was not declared in this scope
  if (lastId == nullptr)
      ^
sharedMemory.cpp:526:48: error: ‘atomic_uint64_t’ is not a member of ‘std’
      allocateSharedMemoryInternal(name, sizeof(std::atomic_uint64_t));
                                                ^
sharedMemory.cpp:528:25: error: expected type-specifier
      lastId = new (ptr) std::atomic_uint64_t(0);
                         ^
sharedMemory.cpp:534:15: error: ‘atomic_uint64_t’ is not a member of ‘std’
     lastId = (std::atomic_uint64_t *)mapSharedMemoryInternal(name);
               ^
sharedMemory.cpp:534:37: error: expected primary-expression before ‘)’ token
     lastId = (std::atomic_uint64_t *)mapSharedMemoryInternal(name);
                                     ^
sharedMemory.cpp: In function ‘void releasePkgData()’:
sharedMemory.cpp:549:2: error: ‘lastId’ was not declared in this scope
  lastId = nullptr;
  ^
make: *** [sharedMemory.o] Error 1
ERROR: compilation failed for package ‘SharedObject’
* removing ‘/home-net/home-1/asaha6@jhu.edu/R/x86_64-pc-linux-gnu-library/4.0/gcc/5.5/SharedObject’
Error: Failed to install 'SharedObject' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp93VFJ4/file51f485eaf18c1/SharedObject_1.3.22.tar.gz’ had non-zero exit status
Execution halted
```

**Comment by Jiefei-Wang** [comment] 2020-10-27 15:23
Thanks @alorchhota , I thought the problem is about the missing header only, but it turns out that CentOS does not have this type defined at all. I have replaced `atomic_uint64_t` with `atomic<std::uint64_t>`. Would you be able to try it again and let me know if it solves your problem?  

Best,
Jiefei

**Comment by alorchhota** [comment] 2020-10-27 15:31
Great. I could install the package successfully. I would try it in my project soon. Thank you!

**Comment by Jiefei-Wang** [comment] 2020-10-28 03:09
Great, glad to hear it. I will keep this issue open for a few days. Please let me know if you have any problem.

Best,
Jiefei

**Comment by Jiefei-Wang** [comment] 2020-11-11 04:27
Closed as the problem has been fixed

**Closed as completed by Jiefei-Wang** 2020-11-11 04:27 UTC
